In [69]:
import pandas as pd
from sklearn.linear_model import LogisticRegression 
from sklearn.linear_model import SGDClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import Imputer

In [42]:
COLUMNS = ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age' ,'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [87]:
df_train = pd.read_csv('train.csv', skipinitialspace=True)
df_test = pd.read_csv('test.csv', skipinitialspace=True)

In [40]:
df_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [79]:
survived = df_train['Survived'].values

In [80]:
age = df_train['Age'].values

In [102]:
pclass = df_train['Pclass'].values
sex = df_train['Sex'].astype('category')
sex.

0        male
1      female
2      female
3      female
4        male
5        male
6        male
7        male
8      female
9      female
10     female
11     female
12       male
13       male
14     female
15     female
16       male
17       male
18     female
19     female
20       male
21       male
22     female
23       male
24     female
25     female
26       male
27       male
28     female
29       male
        ...
861      male
862    female
863    female
864      male
865    female
866    female
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875    female
876      male
877      male
878      male
879    female
880    female
881      male
882    female
883      male
884      male
885    female
886      male
887    female
888    female
889      male
890      male
Name: Sex, dtype: category
Categories (2, object): [female, male]

In [84]:
training = np.column_stack((age, pclass))

imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp = imp.fit(training)

training = imp.transform(training)
training

array([[ 22.        ,   3.        ],
       [ 38.        ,   1.        ],
       [ 26.        ,   3.        ],
       ...,
       [ 29.69911765,   3.        ],
       [ 26.        ,   1.        ],
       [ 32.        ,   3.        ]])

## Define the Logistic Regression Model

In [85]:
clf = SGDClassifier(loss="hinge", penalty="l2")

In [86]:
clf.fit(training, survived)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', n_iter=5, n_jobs=1,
       penalty='l2', power_t=0.5, random_state=None, shuffle=True,
       verbose=0, warm_start=False)

## Prediction

In [89]:
t_age = df_test['Age'].values

In [90]:
t_pclass = df_test['Pclass'].values

In [92]:
testing = np.column_stack((t_age, t_pclass))

imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp = imp.fit(testing)

testing = imp.transform(testing)
testing

array([[ 34.5       ,   3.        ],
       [ 47.        ,   3.        ],
       [ 62.        ,   2.        ],
       [ 27.        ,   3.        ],
       [ 22.        ,   3.        ],
       [ 14.        ,   3.        ],
       [ 30.        ,   3.        ],
       [ 26.        ,   2.        ],
       [ 18.        ,   3.        ],
       [ 21.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 46.        ,   1.        ],
       [ 23.        ,   1.        ],
       [ 63.        ,   2.        ],
       [ 47.        ,   1.        ],
       [ 24.        ,   2.        ],
       [ 35.        ,   2.        ],
       [ 21.        ,   3.        ],
       [ 27.        ,   3.        ],
       [ 45.        ,   3.        ],
       [ 55.        ,   1.        ],
       [  9.        ,   3.        ],
       [ 30.27259036,   1.        ],
       [ 21.        ,   1.        ],
       [ 48.        ,   1.        ],
       [ 50.        ,   3.        ],
       [ 22.        ,   1.        ],
       [ 22.5       ,   3.        ],
       [ 41.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 50.        ,   2.        ],
       [ 24.        ,   2.        ],
       [ 33.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 30.        ,   1.        ],
       [ 18.5       ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 21.        ,   3.        ],
       [ 25.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 39.        ,   3.        ],
       [ 30.27259036,   1.        ],
       [ 41.        ,   3.        ],
       [ 30.        ,   2.        ],
       [ 45.        ,   1.        ],
       [ 25.        ,   3.        ],
       [ 45.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 60.        ,   1.        ],
       [ 36.        ,   3.        ],
       [ 24.        ,   1.        ],
       [ 27.        ,   2.        ],
       [ 20.        ,   2.        ],
       [ 28.        ,   1.        ],
       [ 30.27259036,   2.        ],
       [ 10.        ,   3.        ],
       [ 35.        ,   3.        ],
       [ 25.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 36.        ,   1.        ],
       [ 17.        ,   3.        ],
       [ 32.        ,   2.        ],
       [ 18.        ,   3.        ],
       [ 22.        ,   3.        ],
       [ 13.        ,   1.        ],
       [ 30.27259036,   2.        ],
       [ 18.        ,   3.        ],
       [ 47.        ,   1.        ],
       [ 31.        ,   1.        ],
       [ 60.        ,   1.        ],
       [ 24.        ,   3.        ],
       [ 21.        ,   3.        ],
       [ 29.        ,   3.        ],
       [ 28.5       ,   1.        ],
       [ 35.        ,   1.        ],
       [ 32.5       ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 55.        ,   1.        ],
       [ 30.        ,   2.        ],
       [ 24.        ,   3.        ],
       [  6.        ,   3.        ],
       [ 67.        ,   1.        ],
       [ 49.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   2.        ],
       [ 30.27259036,   3.        ],
       [ 27.        ,   3.        ],
       [ 18.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [  2.        ,   2.        ],
       [ 22.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 27.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 25.        ,   1.        ],
       [ 25.        ,   3.        ],
       [ 76.        ,   1.        ],
       [ 29.        ,   3.        ],
       [ 20.        ,   3.        ],
       [ 33.        ,   3.        ],
       [ 43.        ,   1.        ],
       [ 27.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 26.        ,   3.        ],
       [ 16.        ,   3.        ],
       [ 28.        ,   3.        ],
       [ 21.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 18.5       ,   2.        ],
       [ 41.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 36.        ,   1.        ],
       [ 18.5       ,   3.        ],
       [ 63.        ,   1.        ],
       [ 18.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [  1.        ,   3.        ],
       [ 36.        ,   1.        ],
       [ 29.        ,   2.        ],
       [ 12.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 35.        ,   1.        ],
       [ 28.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 17.        ,   3.        ],
       [ 22.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 42.        ,   2.        ],
       [ 24.        ,   3.        ],
       [ 32.        ,   3.        ],
       [ 53.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 43.        ,   3.        ],
       [ 24.        ,   3.        ],
       [ 26.5       ,   3.        ],
       [ 26.        ,   2.        ],
       [ 23.        ,   3.        ],
       [ 40.        ,   3.        ],
       [ 10.        ,   3.        ],
       [ 33.        ,   1.        ],
       [ 61.        ,   1.        ],
       [ 28.        ,   2.        ],
       [ 42.        ,   1.        ],
       [ 31.        ,   3.        ],
       [ 30.27259036,   1.        ],
       [ 22.        ,   3.        ],
       [ 30.27259036,   1.        ],
       [ 30.        ,   2.        ],
       [ 23.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 60.5       ,   3.        ],
       [ 36.        ,   3.        ],
       [ 13.        ,   3.        ],
       [ 24.        ,   3.        ],
       [ 29.        ,   1.        ],
       [ 23.        ,   3.        ],
       [ 42.        ,   1.        ],
       [ 26.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [  7.        ,   3.        ],
       [ 26.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 41.        ,   2.        ],
       [ 26.        ,   3.        ],
       [ 48.        ,   1.        ],
       [ 18.        ,   3.        ],
       [ 30.27259036,   1.        ],
       [ 22.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 27.        ,   3.        ],
       [ 23.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 40.        ,   3.        ],
       [ 15.        ,   2.        ],
       [ 20.        ,   2.        ],
       [ 54.        ,   1.        ],
       [ 36.        ,   2.        ],
       [ 64.        ,   1.        ],
       [ 30.        ,   2.        ],
       [ 37.        ,   1.        ],
       [ 18.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 27.        ,   1.        ],
       [ 40.        ,   2.        ],
       [ 21.        ,   2.        ],
       [ 17.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 40.        ,   2.        ],
       [ 34.        ,   2.        ],
       [ 30.27259036,   1.        ],
       [ 11.5       ,   3.        ],
       [ 61.        ,   2.        ],
       [  8.        ,   2.        ],
       [ 33.        ,   3.        ],
       [  6.        ,   1.        ],
       [ 18.        ,   3.        ],
       [ 23.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [  0.33      ,   3.        ],
       [ 47.        ,   1.        ],
       [  8.        ,   2.        ],
       [ 25.        ,   2.        ],
       [ 30.27259036,   1.        ],
       [ 35.        ,   3.        ],
       [ 24.        ,   2.        ],
       [ 33.        ,   1.        ],
       [ 25.        ,   3.        ],
       [ 32.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 17.        ,   2.        ],
       [ 60.        ,   2.        ],
       [ 38.        ,   3.        ],
       [ 42.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 57.        ,   1.        ],
       [ 50.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.        ,   2.        ],
       [ 21.        ,   3.        ],
       [ 22.        ,   2.        ],
       [ 21.        ,   3.        ],
       [ 53.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 23.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 40.5       ,   3.        ],
       [ 36.        ,   2.        ],
       [ 14.        ,   2.        ],
       [ 21.        ,   1.        ],
       [ 21.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 39.        ,   1.        ],
       [ 20.        ,   3.        ],
       [ 64.        ,   1.        ],
       [ 20.        ,   3.        ],
       [ 18.        ,   2.        ],
       [ 48.        ,   1.        ],
       [ 55.        ,   1.        ],
       [ 45.        ,   2.        ],
       [ 45.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 41.        ,   1.        ],
       [ 22.        ,   2.        ],
       [ 42.        ,   2.        ],
       [ 29.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [  0.92      ,   2.        ],
       [ 20.        ,   3.        ],
       [ 27.        ,   1.        ],
       [ 24.        ,   3.        ],
       [ 32.5       ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 28.        ,   3.        ],
       [ 19.        ,   2.        ],
       [ 21.        ,   3.        ],
       [ 36.5       ,   3.        ],
       [ 21.        ,   3.        ],
       [ 29.        ,   2.        ],
       [  1.        ,   3.        ],
       [ 30.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 17.        ,   3.        ],
       [ 46.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 26.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 20.        ,   2.        ],
       [ 28.        ,   2.        ],
       [ 40.        ,   2.        ],
       [ 30.        ,   2.        ],
       [ 22.        ,   2.        ],
       [ 23.        ,   3.        ],
       [  0.75      ,   3.        ],
       [ 30.27259036,   3.        ],
       [  9.        ,   3.        ],
       [  2.        ,   3.        ],
       [ 36.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 24.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   1.        ],
       [ 30.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 53.        ,   1.        ],
       [ 36.        ,   3.        ],
       [ 26.        ,   3.        ],
       [  1.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 30.        ,   1.        ],
       [ 29.        ,   3.        ],
       [ 32.        ,   3.        ],
       [ 30.27259036,   2.        ],
       [ 43.        ,   2.        ],
       [ 24.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 64.        ,   1.        ],
       [ 30.        ,   1.        ],
       [  0.83      ,   3.        ],
       [ 55.        ,   1.        ],
       [ 45.        ,   3.        ],
       [ 18.        ,   3.        ],
       [ 22.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 37.        ,   3.        ],
       [ 55.        ,   1.        ],
       [ 17.        ,   3.        ],
       [ 57.        ,   1.        ],
       [ 19.        ,   2.        ],
       [ 27.        ,   3.        ],
       [ 22.        ,   2.        ],
       [ 26.        ,   3.        ],
       [ 25.        ,   3.        ],
       [ 26.        ,   2.        ],
       [ 33.        ,   1.        ],
       [ 39.        ,   1.        ],
       [ 23.        ,   3.        ],
       [ 12.        ,   2.        ],
       [ 46.        ,   1.        ],
       [ 29.        ,   2.        ],
       [ 21.        ,   2.        ],
       [ 48.        ,   2.        ],
       [ 39.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 19.        ,   3.        ],
       [ 27.        ,   3.        ],
       [ 30.        ,   1.        ],
       [ 32.        ,   2.        ],
       [ 39.        ,   3.        ],
       [ 25.        ,   2.        ],
       [ 30.27259036,   3.        ],
       [ 18.        ,   2.        ],
       [ 32.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 58.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 16.        ,   3.        ],
       [ 26.        ,   2.        ],
       [ 38.        ,   3.        ],
       [ 24.        ,   2.        ],
       [ 31.        ,   2.        ],
       [ 45.        ,   1.        ],
       [ 25.        ,   2.        ],
       [ 18.        ,   2.        ],
       [ 49.        ,   2.        ],
       [  0.17      ,   3.        ],
       [ 50.        ,   1.        ],
       [ 59.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 30.        ,   3.        ],
       [ 14.5       ,   3.        ],
       [ 24.        ,   2.        ],
       [ 31.        ,   2.        ],
       [ 27.        ,   3.        ],
       [ 25.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ],
       [ 22.        ,   3.        ],
       [ 45.        ,   1.        ],
       [ 29.        ,   2.        ],
       [ 21.        ,   2.        ],
       [ 31.        ,   1.        ],
       [ 49.        ,   1.        ],
       [ 44.        ,   2.        ],
       [ 54.        ,   1.        ],
       [ 45.        ,   1.        ],
       [ 22.        ,   3.        ],
       [ 21.        ,   2.        ],
       [ 55.        ,   1.        ],
       [  5.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 26.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 19.        ,   3.        ],
       [ 30.27259036,   2.        ],
       [ 24.        ,   2.        ],
       [ 24.        ,   3.        ],
       [ 57.        ,   2.        ],
       [ 21.        ,   3.        ],
       [  6.        ,   3.        ],
       [ 23.        ,   1.        ],
       [ 51.        ,   1.        ],
       [ 13.        ,   3.        ],
       [ 47.        ,   2.        ],
       [ 29.        ,   3.        ],
       [ 18.        ,   1.        ],
       [ 24.        ,   3.        ],
       [ 48.        ,   1.        ],
       [ 22.        ,   3.        ],
       [ 31.        ,   3.        ],
       [ 30.        ,   1.        ],
       [ 38.        ,   2.        ],
       [ 22.        ,   1.        ],
       [ 17.        ,   1.        ],
       [ 43.        ,   1.        ],
       [ 20.        ,   2.        ],
       [ 23.        ,   2.        ],
       [ 50.        ,   1.        ],
       [ 30.27259036,   3.        ],
       [  3.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 37.        ,   1.        ],
       [ 28.        ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 39.        ,   1.        ],
       [ 38.5       ,   3.        ],
       [ 30.27259036,   3.        ],
       [ 30.27259036,   3.        ]])

In [93]:
clf.predict(testing)

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0])